웹서비스/yunji_desk1/webtoonitda/urls.py
from django.urls import path

import webtoonitda
from webtoonitda.views import base_views

app_name = 'webtoonitda'

urlpatterns = [
    # base
    #path('', base_views.index, name='index'),

    path('index/', base_views.index, name='index'),  # http://127.0.0.1:8000/webtoonitda/index
    path('service_summary/', base_views.service_summary, name='service_summary'),

    path('show_num_reviews/<str:lang>/<str:platform>/<str:webtoon>', base_views.show_num_reviews, name="show_num_reviews"),
    path('get_best_episodes_by_reviews/<str:lang>/<str:platform>/<str:webtoon>', base_views.get_best_episodes_by_reviews, name="get_best_episodes_by_reviews"),
    path('get_best_episodes/<str:lang>/<str:platform>/<str:webtoon>', base_views.get_best_episodes, name="get_best_episodes"),

    path('show_keywords/<str:lang>/<str:platform>/<str:webtoon>', base_views.show_keywords, name="show_keywords"),

#윤지 작성
    path('ep_review', base_views.ep_review, name='ep_review'),
    path('ep_search', base_views.ep_search, name='ep_search'),
]

웹서비스/yunji_desk1/webtoonitda/views/base_views.py
import logging
import os

from django.http import HttpResponse
from django.shortcuts import redirect, render

from webtoonitda.models import Webtoon
from webtoonitda.views.naver_webtoon import get_webtoon_titleId, get_top10_point_participants, get_top10_num_reviews, \
    get_titleId_num_episodes
from webtoonitda.views.review_webtoon import get_reviews


logger = logging.getLogger('webtoonitda')

def login(request):
    return render(request, 'common/login.html')

def index(request):
    if request.user.is_authenticated:
        return render(request, 'webtoonitda/index.html')
    else:
        return render(request, 'common/login.html')

def service_summary(request):
    if request.method == 'POST':
        print("service_summary POST")

        lang = request.POST.get('lang')
        platform = request.POST.get('platform')
        webtoon = request.POST.get('webtoon')

        # db 생성
        # Webtoon.objects.create(lang=lang, platform=platform, webtoon=webtoon)

        context = {
            'lang': lang,
            'platform': platform,
            'webtoon': webtoon,
        } # 템플릿에 전달할 데이터를 세팅할 수 있는 오브젝트
        return render(request, 'webtoonitda/service_summary.html', context)

def show_num_reviews(request, lang, platform, webtoon):
    context = {
        'lang': lang,
        'platform': platform,
        'webtoon': webtoon,
    }  # 템플릿에 전달할 데이터를 세팅할 수 있는 오브젝트
    return render(request, 'webtoonitda/show_num_reviews.html', context)

def get_best_episodes_by_reviews(request, lang, platform, webtoon):

    print(os.getcwd())

    # 1. 동적으로 크롤링하여 결과 보여주기
    chromedriver_path = 'c:\Temp\chromedriver.exe'
    # titleId = get_webtoon_titleId(chromedriver_path, platform, lang, webtoon)
    # print("titleId: " + str(titleId))

    DATA_DIR = os.getcwd() + "/media/"
    USE_CSV_FILE = True

    title_id, num_episodes = get_titleId_num_episodes(chromedriver_path, platform, lang, webtoon, USE_CSV_FILE)

    df = get_top10_num_reviews(chromedriver_path, platform, lang, title_id, num_episodes, USE_CSV_FILE)

    print("Done")

    context = {
        'lang': lang,
        'platform': platform,
        'webtoon': webtoon,
        'df': df[:10].to_html(justify='center')
    }  # 템플릿에 전달할 데이터를 세팅할 수 있는 오브젝트

    return render(request, 'webtoonitda/show_best_episodes_by_reviews.html', context)

def show_keywords(request, lang, platform, webtoon):

    print("show_keywordss lang: " + lang)
    print("show_keywordss platform: " + platform)
    print("show_keywordss webtoon: " + webtoon)

    context = {
        'lang': lang,
        'platform': platform,
        'webtoon': webtoon,
    }  # 템플릿에 전달할 데이터를 세팅할 수 있는 오브젝트

    return render(request, 'webtoonitda/show_keywords.html', context)

def get_best_episodes(request, lang, platform, webtoon):
    # 1. 동적으로 크롤링하여 결과 보여주기
    chromedriver_path = 'c:\Temp\chromedriver.exe'
    titleId = get_webtoon_titleId(chromedriver_path, platform, lang, webtoon)
    print("titleId: " + str(titleId))
    df = get_top10_point_participants(chromedriver_path, platform, lang, titleId)
    print("Done")

    context = {'df': df[:10].to_html(justify='center')}
    return render(request, 'webtoonitda/show_best_episodes.html', context)

    # 2. csv 저장된 csv 파일에서 가져와서 보여주기

    # 저장된 csv 파일에서 가져오기
    # df = pd.read_csv('C:\MyJupiter\삼성멀티캠\_Django\workspace\webtoonsite\webtoon1\전독시_인기_에피소드.csv', index_col = 0)

    # DB 에 data를 생성하기
    # for i in range(10):
    #     BestEpisodes.objects.create(title=df['Title'][i], point=df['Point'][i], participant=df['Participant'][i])
    #     print(df['Point'][i])
    #
    # # DB 에서 데이터 가져오기
    # all_episode = BestEpisodes.objects.all().order_by('-id')

    context = {'df': df[:10].to_html(justify='center')}
    return render(request, 'webtoonitda/show_best_episodes.html', context)

#윤지
def ep_review(request):
  return render(request, 'webtoonitda/ep_review.html')


import pandas as pd
def ep_search(request):
    if request.method == 'POST':
          keyword = request.POST.get('keyword')
          print("ep_review POST" + keyword)
          DATA_DIR = os.getcwd() + "/media/"

          print("Read csv file.")
          filepath = DATA_DIR + "omniscient-reader_Episode_kr_21.csv"
          df = pd.read_csv(filepath)

          test = df[df['Review'].str.contains(keyword)]  # df에 keyword파라미터 받음
          df = test.sample(10)  # 원하는 개수만큼 추출
          print(type(df))



          context = {
              'df': df[:10].to_html(justify='center')


          } # 템플릿에 전달할 데이터를 세팅할 수 있는 오브젝트

          # return HttpResponse("ep_search keyword:" + title)
    return render(request, 'webtoonitda/show_21_episodes.html', context)
# )

웹서비스/yunji_desk1/webtoonitda/views/naver_webtoon.py
# ---
# jupyter:
#   jupytext:
#     formats: ipynb,py:light
#     text_representation:
#       extension: .py
#       format_name: light
#       format_version: '1.5'
#       jupytext_version: 1.14.0
#   kernelspec:
#     display_name: nlp
#     language: python
#     name: nlp
# ---

# +
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.keys import Keys
from webdriver_manager.chrome import ChromeDriverManager
from bs4 import BeautifulSoup as bs
import requests
import pandas as pd
import matplotlib.pyplot as plt
plt.rc('font', family='NanumGothic')
import os
import time
from glob import glob

pd.set_option("display.max_rows", 1000)
pd.set_option("display.max_columns", 1000)
pd.options.display.float_format = '{:.2f}'.format
# -

"""
set_configuration : Argument setting 하는 함수
get_webtoon_titleId : 웹툰명으로 타이틀id를 구하는 함수
get_num_pages : 에피소드별 댓글 페이지 개수를 구하는 함수
get_num_episodes : 웹툰의 에피소드 개수를 구하는 함수
get_comments : 에피소드의 댓글을 수집하는 함수

get_all_comments : 모든 에피소드의 댓글을 수집하는 함수

merge_csv_files : 에피소드별 댓글 CSV 파일을 통합하는 함수

get_point_participants : 에피소드별 별점과 참여자수를 구하는 함수
get_num_reviews : 에피소드별 댓글 개수를 구하는 함수

get_top10_point_participants : 에피소드별 별점과 참여자수가 가장 높은 에피소드 top10을 반환하는 함수

"""


def get_webtoon_titleId(chromedriver_path, platform, lang, titleName):
    """
    웹툰명으로 타이틀id를 구하는 함수
    """
    if lang == 'kr':
        print(titleName,"의 titleId를 구합니다.")
    elif lang == 'en':
        print("Get the title number of the ", titleName)
        
    # chrome driver setting    
    service = Service(executable_path=chromedriver_path)

    TIMEOUT = 1 
    driver = webdriver.Chrome(service=service)  
    
    if platform == 'naver' and lang == 'kr':
        base_url = 'https://comic.naver.com/index' 
    elif platform == 'naver' and lang == 'en':
        base_url = 'https://www.webtoons.com/en/' 
        
    print(base_url)
    driver.get(base_url)
    driver.implicitly_wait(TIMEOUT)   
    
    search_query = titleName

    if lang == 'kr':
        # https://comic.naver.com/search?keyword=전지적+독자+시점
        driver.find_element(by=By.CSS_SELECTOR, value='input#gnb\.keyword').clear() # 검색창 초기화
        driver.find_element(by=By.CSS_SELECTOR, value='input#gnb\.keyword').send_keys(search_query)  # 검색어 입력 
        driver.find_element(by=By.CSS_SELECTOR, value= '#search_bar_button > span').click()  # 검색 버튼 클릭
        time.sleep(1)        
        
        # 웹툰 선택
        driver.find_element(by=By.CSS_SELECTOR, value='#content > div.searchTxt > ul > li:nth-child(2) > a').click()
        time.sleep(1)  

        names = driver.find_elements(by=By.CSS_SELECTOR, value='#content ul h5 > a')
        for name in names:
            if name.text == titleName:
                href = name.get_attribute('href')
                titleId = href.split('?titleId=')[1]
                print(titleName, 'titleId ', titleId)
            
    elif lang == 'en':
        # https://www.webtoons.com/en/search?keyword=Omniscient%20Reader
        driver.find_element(by=By.CSS_SELECTOR, value= 'a.btn_search').click()  # 검색 버튼 클릭
        driver.find_element(by=By.CSS_SELECTOR, value='input.input_search').clear() # 검색창 초기화
        driver.find_element(by=By.CSS_SELECTOR, value='input.input_search').send_keys(search_query)  # 검색어 입력
        driver.find_element(by=By.CSS_SELECTOR, value='input.input_search').send_keys(Keys.RETURN)  # Enter Key 입력 
              
        # ORIGINALS 선택
        names = driver.find_elements(by=By.CSS_SELECTOR, value='#content > div.card_wrap.search._searchResult > ul > li > a')
        time.sleep(1) 
        # CANVAS 선택
        #elements = driver.find_elements(by=By.CSS_SELECTOR, value='#content > div.card_wrap.search._searchResult > div.challenge_lst.search > ul  a > p.subj')
        for name in names:
            subj = name.find_element(by=By.CSS_SELECTOR, value='div > p.subj')
            if subj.text == titleName:
                href = name.get_attribute('href')
                titleId = href.split('?titleNo=')[1]
                print(titleName, 'titleId ', titleId)   
    driver.quit()
    return titleId


def get_num_episodes(chromedriver_path, platform = 'naver', lang = 'kr', titleId = 747269):
    """
    웹툰의 에피소드 개수를 구하는 함수
    """    
    if lang == 'kr':
        print('titleId가 ', titleId, "인 웹툰의 episode 개수를 구합니다.")
    elif lang == 'en':
        print("Get the number of episodes of titleId, ", titleId)
        
    # chrome driver setting    
    service = Service(executable_path=chromedriver_path)    
    TIMEOUT = 1 
    driver = webdriver.Chrome(service=service)
    
    if platform == 'naver' and lang == 'kr':
        base_url = 'https://comic.naver.com/webtoon/list?' + 'titleId=' + str(titleId)
    elif platform == 'naver' and lang == 'en':    
        base_url = 'https://www.webtoons.com/en/action/omniscient-reader/list?' + 'title_no=' + str(titleId)
        
    print(base_url)
    driver.get(base_url)
    driver.implicitly_wait(TIMEOUT)   
       
    # Get the total number of pages
    if lang == 'kr':
        pages = driver.find_element(by=By.CSS_SELECTOR, value="#content > table > tbody > tr:nth-child(2) > td.title > a")
        num_episodes = int(pages.text.split('.')[0]) + 1
        print("num_episodes:", num_episodes)
    elif lang == 'en':  
        element = driver.find_element(by=By.CSS_SELECTOR, value="li._episodeItem")
        num_episodes = int(element.get_attribute("data-episode-no"))
        print("num_episodes:", num_episodes)
        
    driver.quit()
    return num_episodes


def get_comments(driver, df, lang = 'kr', titleId = 747269, episode_no = 1):
    """
    에피소드의 댓글을 수집하는 함수
    """        
    
    if lang == 'kr':
        base_url = 'https://comic.naver.com/webtoon/detail?'
        episode_url = base_url + 'titleId=' + str(titleId) + '&no='+str(episode_no)
    elif lang == 'en':
        # https://www.webtoons.com/en/action/omniscient-reader/episode-118/viewer?title_no=2154&episode_no=119
        base_url = 'https://www.webtoons.com/en/action/omniscient-reader/episode-'
        episode_url = base_url + str(episode_no -1) + '/viewer?title_no=' + str(titleId) + '&episode_no='+str(episode_no)        
        
    print(episode_url)
    driver.get(episode_url)
    driver.implicitly_wait(1)
    
    if lang == 'kr':
        # 댓글창에 해당하는 프레임 선택
        driver.switch_to.frame('commentIframe')

        # 수집 편의를 위한 클린봇 댓글 필터링 기능 해제
        # (클린봇이 부적절한 표현을 감지한 댓글입니다.) 제거
        driver.find_element(By.CLASS_NAME,'u_cbox_cleanbot_setbutton').click()
        time.sleep(0.2)
        driver.find_element(By.CLASS_NAME,'u_cbox_layer_cleanbot2_checkbox').click()
        time.sleep(0.2)
        driver.find_element(By.CLASS_NAME,'u_cbox_layer_cleanbot2_extrabtn').click()
        time.sleep(0.2)

        # 전체 댓글 클릭
        driver.find_element(By.CSS_SELECTOR,'#cbox_module > div > div.u_cbox_view_comment > a').click()
        time.sleep(0.5)        
    elif lang == 'en':
        # No iframe
        # No Cleanbot filtering setting
        # No need to click "전체 댓글"        
        pass 
    
    # Move to the last page and Get the total number of pages
    driver.find_element(By.CSS_SELECTOR,'#cbox_module > div > div.u_cbox_paginate > div > a.u_cbox_next.u_cbox_next_end').click()
    time.sleep(1)
    
    u_cbox_num_page = driver.find_element(By.CSS_SELECTOR,'#cbox_module > div > div.u_cbox_paginate > div > strong > span.u_cbox_num_page')
    time.sleep(1)
    num_pages = u_cbox_num_page.text
    print("num_pages:",num_pages)
  
    # Move to the first page
    driver.find_element(By.CSS_SELECTOR,'#cbox_module > div > div.u_cbox_paginate > div > a.u_cbox_pre.u_cbox_pre_end').click()
    time.sleep(0.5)

    for page in range(int(num_pages)):
        if lang == 'kr':        
            # switch to the recent tab
            driver.switch_to.window(driver.window_handles[-1]) 
            driver.switch_to.frame("commentIframe")        
        
        soup = bs(driver.page_source,"html.parser")

        # Extract dates
        dates = soup.findAll("span", {"class":["u_cbox_date"]})
        dates = [date.text for date in dates]        

        # Extract reveiws
        reviews = soup.findAll("span", {"class":["u_cbox_contents"]})
        reviews = [review.get_text() for review in reviews]

        df_page = pd.DataFrame(data=[], columns=['Episode','Date','Review'])       
        df_page['Date'] = dates
        df_page['Review'] = reviews
        df_page['Episode'] = df_page['Episode'].fillna(int(episode_no))
        
        df = pd.concat([df,df_page])      
        print('.', end='')

        if (page+1) == int(num_pages):
            return df
        
        # Move to the next page
        driver.find_element(By.CSS_SELECTOR, "#cbox_module > div > div.u_cbox_paginate > div > strong + a").click()        
        time.sleep(0.2)
    return df


def get_num_pages(driver, lang = 'kr', titleId = 747269, episode_no = 1):
    """
    에피소드별 댓글 페이지 개수를 구하는 함수
    """
    if lang == 'kr':
        base_url = 'https://comic.naver.com/webtoon/detail?'
        episode_url = base_url + 'titleId=' + str(titleId) + '&no='+str(episode_no)
    elif lang == 'en':
        # https://www.webtoons.com/en/action/omniscient-reader/episode-118/viewer?title_no=2154&episode_no=119
        base_url = 'https://www.webtoons.com/en/action/omniscient-reader/episode-'
        episode_url = base_url + str(episode_no -1) + '/viewer?title_no=' + str(titleId) + '&episode_no='+str(episode_no)        
        
    print(episode_url)
    driver.get(episode_url)
    driver.implicitly_wait(1)
    
    if lang == 'kr':
        # 댓글창에 해당하는 프레임 선택
        driver.switch_to.frame('commentIframe')

        # 수집 편의를 위한 클린봇 댓글 필터링 기능 해제
        # (클린봇이 부적절한 표현을 감지한 댓글입니다.) 제거
        driver.find_element(By.CLASS_NAME,'u_cbox_cleanbot_setbutton').click()
        time.sleep(0.2)

웹서비스/yunji_desk1/templates/webtoonitda/ep_review.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}

<div class="container my-3">
    <div class="row my-3">
        <div class="col-6">
            <h2> 에피소드 댓글 분석</h2>
            <h5> {{title}} </h5>

        </div>
    </div>


    <style>
h1 {
    text-align: center;
}

.background{
    background-color: white;
    column-count : 2;
}


    </style>

    <!--    키워드 검색 만들기-->
    <!--<div class="row" style="float:left;">-->
    <div>
        <div class="row">
            <!-- 워드클라우드-->
            <div class="card mb-4">
                <div class="card-header">전지적 독자 시점</div>
                <div class="card-body">
                    <div class="row">

                        <h3> 21화 키워드 분석 </h3>

                        <img src="/media/kr 전독시 EP 21(okt) size.jpg" style="width: auto; height: auto;"/>

                    </div>
                </div>
                <!--        Search section-->
                <form action="{% url 'webtoonitda:ep_search' %}" method="POST">
                    {% csrf_token %}
                    <div class="card mb-5">
                        <div class="card-header">키워드를 입력하세요.</div>
                        <div class="card-body">

                            <form>
                                <input type="text" name="keyword" value="keyword">
                            </form>

                            <br>
                            <br>
                            <button type="submit" class="btn btn-primary">검색
                            </button>
                        </div>
                        <div id="result"></div>
                    </div>
                </form>
            </div>
            <div class="col-3">

            </div>
        </div>


        <div class="container my-3">
            <a href="javascript:history.back();">뒤로가기</a>
        </div>
    </div>
    </form>
</div>
{% endblock %}

웹서비스/yunji_desk1/templates/webtoonitda/service_summary.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}
<div class="container my-3">
    <h1> webtoon service summary</h1>

<!--    {% if platform != 'naver' and webtoon != '전지적 독자 시점' %}-->
<!--         <h2> 앗앗앗! {{webtoon}}에 대해 아직 준비된 서비스가 없습니다.</h2>-->
<!--    {% else %}-->
        {% if lang == 'kr' %}
        <h5> 한글 , {{platform}} , {{webtoon}} 분석을 시작합니다.</h5>
        {% elif lang == 'en' %}
        <h5> 영어 , {{platform}} , {{webtoon}} 분석을 시작합니다.</h5>
        {% endif %}
<!--    {% endif %}-->

</div>

<!-- Categories widget-->
<div class="card mb-4">
    <div class="card-header">Categories</div>
    <div class="card-body">
        <div class="row">
            <div class="col-sm-6">
                <ul class="list-unstyled mb-0">
                    <h3>
                        <li><a href="{% url 'webtoonitda:show_num_reviews' lang platform webtoon %}">
                            전체 댓글 수 추이</a></li>
                    </h3>
                    <br>
                    <h3>
                        <li><a href="#!">전체 평점수 추이</a></li>
                    </h3>
                    <br>
                    <h3>
                        <li><a href="#!">전체 참여도수 추이</a></li>
                    </h3>
                    <br>
                    <h3>
                        <li><a href="{% url 'webtoonitda:ep_review' %}">원본 댓글 추출</a></li>
                    </h3>
                    <br>

                </ul>
            </div>
            <div class="col-sm-6">
                <ul class="list-unstyled mb-0">
                    <h3>
                        <li><a href="{% url 'webtoonitda:get_best_episodes_by_reviews' lang platform webtoon %}">
                            댓글 수 에피소드 Top10
                            순위 Top10</a></li>
                    </h3>
                    <br>
                    <h3>
                        <li><a href="{% url 'webtoonitda:get_best_episodes' lang platform webtoon %}">
                            평점수 에피소드 Top10</a></li>
                    </h3>
                    <br>
                    <h3>
                        <li><a href="#!">참여도수 에피소드 Top10</a></li>
                    </h3>
                    <br>

                    <h3>
                        <li><a href="{% url 'webtoonitda:show_keywords' lang platform webtoon %}">중요 / 유사 키워드 Top10</a>
                        </li>
                    </h3>
                    <br>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="container my-3">
    <a href="javascript:history.back();">뒤로가기</a>
</div>


<div class="col-sm-4 col-lg-3">

</div>


{% endblock %}
{% block script %}
<script type='text/javascript'>

</script>
{% endblock %}

웹서비스/yunji_desk1/templates/webtoonitda/show_best_episodes.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}

<div class="container my-3">
    <div class="row my-3">
        <div class="col-6">
            <h2> 댓글 수 인기 에피소드 순위 top 10</h2>
            {% if lang == 'kr' %}
            <h5> 한글 , {{platform}} , {{webtoon}} 분석을 시작합니다.</h5>
            {% elif lang == 'en' %}
            <h5> 영어 , {{platform}} , {{webtoon}} 분석을 시작합니다.</h5>
            {% endif %}
        </div>
    </div>


</div>
<form id="searchForm" method="get" action="{% url 'index' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>

{{ df|safe}}

<div>
    <img src="/media/kr_top10_num_reviews.png"/>
    {{webtoonitda.kr_top10_num_reviews.png}}
</div>

<div class="container my-3">
    <a href="javascript:history.back();">뒤로가기</a>
</div>

</form>

{% endblock %}

웹서비스/yunji_desk1/templates/webtoonitda/show_best_episodes_by_reviews.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}

<div class="container my-3">
    <div class="row my-3">
        <div class="col-6">
            {% if platform != 'naver' and webtoon != '전지적 독자 시점' %}
            <h2> 앗앗앗! {{webtoon}} 플랫폼 {{webtoon}}에 대해 아직 준비된 서비스가 없습니다.</h2>
            {% else %}
            <h2> 에피소드별 댓글 추이</h2>
            {% if lang == 'kr' %}
            <h5> 한글 , {{platform}} , {{webtoon}} 분석 결과입니다.</h5>
            {% elif lang == 'en' %}
            <h5> 영어 , {{platform}} , {{webtoon}} 분석 결과입니다.</h5>
            {% endif %}
            {% endif %}

        </div>
    </div>


</div>
<form id="searchForm" method="get" action="{% url 'webtoonitda:index' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>

<!--{{ df|safe}}-->

<div>

    {% if lang == 'kr' %}
    <!--    <h2> 한글</h2>-->
    <img src="/media/kr_top10_num_reviews.png"/>
    {% elif lang == 'en' %}
    <!--    <h2> 영어</h2>-->
    <img src="/media/en_top10_num_reviews.png"/>
    {% else %}
    <!--    <h2> 다른 언어</h2>-->
    <h2> 앗! {{lang}}에 대해 아직 준비된 서비스가 없습니다.</h2>
    {% endif %}

</div>

<div class="container my-3">
    <a href="javascript:history.back();">뒤로가기</a>
</div>

</form>

{% endblock %}

웹서비스/yunji_desk1/templates/webtoonitda/show_keywords.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}


<style>
h1 {
    text-align: center;
}

.background{
    background-color: white;
    column-count : 2;
}

</style>
<div class="container my-3">
    <div class="row my-3">
        <div class="col-6">
            <h2> 중요/유사 키워드 Top10 </h2>
            {% if lang == 'kr' %}
            <h5> 한글 , {{platform}} , {{webtoon}} 분석을 시작합니다.</h5>
            {% elif lang == 'en' %}
            <h5> 영어 , {{platform}} , {{webtoon}} 분석을 시작합니다.</h5>
            {% endif %}
        </div>
    </div>


</div>
<form id="searchForm" method="get" action="{% url 'webtoonitda:index' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>

{{ df|safe}}

<div class="row">
    {% if lang == 'kr' %}
    <div class="background">
        <div class="col-6">
            <img src="/media/Review_top10_가로바차트_한글.png" style="width: auto; height: auto;"/>
        </div>

        <div class="col-6">
            <img src="/media/Review_top10_파이차트1_한글.png" style="width: auto; height: auto;"/>
        </div>
    </div>
      {% elif lang == 'en' %}


      {% endif %}
    <div class="container my-3">
        <a href="javascript:history.back();">뒤로가기</a>
    </div>
</div>
</form>

{% endblock %}

웹서비스/yunji_desk1/templates/webtoonitda/show_num_reviews.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}

<div class="container my-3">
    <div class="row my-3">
        <div class="col-6">
            {% if platform != 'naver' and webtoon != '전지적 독자 시점' %}
            <h2> 앗앗앗! {{webtoon}} 플랫폼 {{webtoon}}에 대해 아직 준비된 서비스가 없습니다.</h2>
            {% else %}
            <h2> 에피소드별 댓글 추이</h2>
            {% if lang == 'kr' %}
            <h5> 한글 , {{platform}} , {{webtoon}} 분석 결과입니다.</h5>
            {% elif lang == 'en' %}
            <h5> 영어 , {{platform}} , {{webtoon}} 분석 결과입니다.</h5>
            {% endif %}
            {% endif %}

        </div>
    </div>


</div>
<form id="searchForm" method="get" action="{% url 'webtoonitda:index' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>

{{ df|safe}}

<div>

    {% if lang == 'kr' %}
    <!--    <h2> 한글</h2>-->
    <img src="/media/kr_num_reviews.png"/>
    {% elif lang == 'en' %}
    <!--    <h2> 영어</h2>-->
    <img src="/media/en_num_reviews.png"/>
    {% else %}
    <!--    <h2> 다른 언어</h2>-->
    <h2> 앗! {{lang}}에 대해 아직 준비된 서비스가 없습니다.</h2>
    {% endif %}

</div>

<div class="container my-3">
    <a href="javascript:history.back();">뒤로가기</a>
</div>

</form>

{% endblock %}