웹서비스/webtoonitda/pybo/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views

app_name = 'pybo'

urlpatterns = [
    # base
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),

    # question
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),

    # answer
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
    path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name='answer_vote'),
]

웹서비스/webtoonitda/webtoonitda/urls.py
from django.urls import path

import webtoonitda
from webtoonitda.views import base_views

app_name = 'webtoonitda'

urlpatterns = [
    # base
    #path('', base_views.index, name='index'),

    path('index/', base_views.index, name='index'),  # http://127.0.0.1:8000/webtoonitda/index
    path('service_summary/', base_views.service_summary, name='service_summary'),

    path('show_num_reviews/<str:lang>/<str:platform>/<str:webtoon>', base_views.show_num_reviews, name="show_num_reviews"),
    path('show_best_episodes_by_reviews/<str:lang>/<str:platform>/<str:webtoon>', base_views.show_best_episodes_by_reviews, name="show_best_episodes_by_reviews"),
    path('show_best_episodes_by_points/<str:lang>/<str:platform>/<str:webtoon>', base_views.show_best_episodes_by_points, name="show_best_episodes_by_points"),
    path('show_participants/<str:lang>/<str:platform>/<str:webtoon>',base_views.show_participants, name="show_participants"),

    path('show_keywords/<str:lang>/<str:platform>/<str:webtoon>', base_views.show_keywords, name="show_keywords"),
    path('show_topic_keywords/<str:lang>/<str:platform>/<str:webtoon>', base_views.show_topic_keywords, name="show_topic_keywords"),
    path('episode_page', base_views.episode_page, name="episode_page"),
    path('show_similarity', base_views.show_similarity, name="show_similarity"),

#윤지 작성
    path('ep_review', base_views.ep_review, name='ep_review'),
    path('ep_search', base_views.ep_search, name='ep_search'),
]

웹서비스/webtoonitda/webtoonitda/models.py
from django.db import models

# Create your models here.
class Webtoon(models.Model):
    lang = models.CharField(max_length=100 , verbose_name="언어")
    platform = models.CharField(max_length=100, verbose_name="플랫폼")
    webtoon = models.CharField(max_length=100, verbose_name="웹툰")

    # page title	 point	participant
    # page = models.IntegerField(verbose_name="페이지번호")
    # title = models.CharField(max_length=100 , verbose_name="제목")
    #
    # # 표현할 수 있는 숫자의 수(max_digits)와 소수점 위치(decimal_places)를 지정
    # point = models.DecimalField( max_digits=3, decimal_places=2,verbose_name="평점")
    #
    # participant = models.IntegerField( verbose_name="참여자수")

    def __str__(self):
        return self.webtoon

    class Meta:
        db_table = 'Webtoon'
        verbose_name = "Webtoon"  #관리자페이지에 모델 관리에 표시되는 이름
        verbose_name_plural = "Webtoon"   #기본적으로 영어기준 복수로 모델명이 표시가 되므로

웹서비스/webtoonitda/webtoonitda/views/base_views.py
import logging
import os

import pandas as pd
from django.http import HttpResponse
from django.shortcuts import redirect, render

from webtoonitda.models import Webtoon
from webtoonitda.views.naver_webtoon import get_webtoon_titleId, get_top10_point_participants, get_top10_num_reviews, \
    get_titleId_num_episodes, show_iplot_best_episodes_by_points, show_best_by_points
from webtoonitda.views.review_webtoon import get_reviews

logger = logging.getLogger('webtoonitda')

def login(request):
    return render(request, 'common/login.html')

def index(request):
    if request.user.is_authenticated:
        return render(request, 'webtoonitda/index.html')
    else:
        return render(request, 'common/login.html')

def show_similarity(request):
    print("show_similarity")
    return render(request, 'webtoonitda/show_similarity.html')


def episode_page(request):
    if request.method == 'POST':
        episode = request.POST.get('episode')
        print("episode " + str(episode) + "를 분석합니다.")

        context = {
            'episode': str(episode)
        } # 템플릿에 전달할 데이터를 세팅할 수 있는 오브젝트
        return render(request, 'webtoonitda/episode_page.html', context)

def service_summary(request):
    if request.method == 'POST':
        print("service_summary POST")

        lang = request.POST.get('lang')
        platform = request.POST.get('platform')
        webtoon = request.POST.get('webtoon')

        # db 생성
        # Webtoon.objects.create(lang=lang, platform=platform, webtoon=webtoon)

        context = {
            'lang': lang,
            'platform': platform,
            'webtoon': webtoon,
        } # 템플릿에 전달할 데이터를 세팅할 수 있는 오브젝트
        return render(request, 'webtoonitda/service_summary.html', context)

def show_num_reviews(request, lang, platform, webtoon):
    context = {
        'lang': lang,
        'platform': platform,
        'webtoon': webtoon,
    }  # 템플릿에 전달할 데이터를 세팅할 수 있는 오브젝트
    return render(request, 'webtoonitda/show_num_reviews.html', context)

def show_best_episodes_by_reviews(request, lang, platform, webtoon):

    print(os.getcwd())

    # 1. 동적으로 크롤링하여 결과 보여주기

    # chromedriver_path = '/media/kr/'  # 윤지 크롬드라이브 경로
    chromedriver_path = 'c:\python\chromedriver.exe' #윤지 크롬드라이브 경로
    # chromedriver_path = 'c:\Temp\chromedriver.exe' # 선미님 크롬드라이브 경로
    # titleId = get_webtoon_titleId(chromedriver_path, platform, lang, webtoon)
    # print("titleId: " + str(titleId))

    DATA_DIR = os.getcwd() + "/media/kr/"
    USE_CSV_FILE = True

    title_id, num_episodes = get_titleId_num_episodes(chromedriver_path, platform, lang, webtoon, USE_CSV_FILE)

    df = get_top10_num_reviews(chromedriver_path, platform, lang, title_id, num_episodes, USE_CSV_FILE)

    print("Done")

    context = {
        'lang': lang,
        'platform': platform,
        'webtoon': webtoon,
        'df': df[:10].to_html(justify='center')
    }  # 템플릿에 전달할 데이터를 세팅할 수 있는 오브젝트

    return render(request, 'webtoonitda/show_best_episodes_by_reviews.html', context)

def show_keywords(request, lang, platform, webtoon):

    print("show_keywords lang: " + lang)
    print("show_keywords platform: " + platform)
    print("show_keywords webtoon: " + webtoon)

    context = {
        'lang': lang,
        'platform': platform,
        'webtoon': webtoon,
    }  # 템플릿에 전달할 데이터를 세팅할 수 있는 오브젝트

    return render(request, 'webtoonitda/show_keywords.html', context)

def show_topic_keywords(request, lang, platform, webtoon):

    print("show_topic_keywords lang: " + lang)
    print("show_topic_keywords platform: " + platform)
    print("show_topic_keywords webtoon: " + webtoon)

    context = {
        'lang': lang,
        'platform': platform,
        'webtoon': webtoon,
    }  # 템플릿에 전달할 데이터를 세팅할 수 있는 오브젝트

    return render(request, 'webtoonitda/show_topic_keywords.html', context)

def show_participants(request, lang, platform, webtoon):

    print("show_topic_keywords lang: " + lang)
    print("show_topic_keywords platform: " + platform)
    print("show_topic_keywords webtoon: " + webtoon)

    context = {
        'lang': lang,
        'platform': platform,
        'webtoon': webtoon,
    }  # 템플릿에 전달할 데이터를 세팅할 수 있는 오브젝트

    return render(request, 'webtoonitda/show_participants.html', context)
def show_best_episodes_by_points(request, lang, platform, webtoon):

    USE_CSV_FILE = False

    # 1. 동적으로 크롤링하여 결과 보여주기
    DATA_DIR = os.getcwd() + "/media/kr/"
    if USE_CSV_FILE:
        # 저장된  csv 파일을 읽어온다.
        df = pd.read_csv(DATA_DIR + 'kr_전지적 독자 시점_best_by_points.csv')
    else:
        # 크롤링 한다.
        chromedriver_path = 'c:\python\chromedriver.exe' #윤지 크롬드라이브 경로
        # chromedriver_path = 'c:\Temp\chromedriver.exe' #선미님 크롬드라이브 경로
        titleId = get_webtoon_titleId(chromedriver_path, platform, lang, webtoon)
        print("titleId: " + str(titleId))
        df = get_top10_point_participants(chromedriver_path, platform, lang, titleId)
        print("Done")

        # 결과를 저장한다
        df.to_csv(DATA_DIR + '{lang}_{webtoon}_best_by_points.csv'.format(lang=lang, webtoon=webtoon))
        print("Saved.")

    df['Episode'] = df.index
    df['Episode'] = df['Episode'] + 1

    df = df.drop('Point', axis=1)
    df_top = df

    # df = df.drop('Point', axis=1)
    # df = df.sort_values(by=['Participant'], ascending=False)
    #
    # df_reverse = df.loc[::-1]

    # 시각화 파일을 저장한다.
    #filename = lang + '_'+ webtoon + '_best_episodes_by_points.png'
    filename = "generated.png"
    filepath = DATA_DIR + filename
    show_best_by_points(df_top[:10], filepath, webtoon)

    #filename = 'kr_iplot_best_episodes_by_points.png'
    #df = df.set_index('Title')
    #show_iplot_best_episodes_by_points(df_reverse, filename)

    context = {
        'df': df[:10].to_html(justify='center'),
        'filename': filename,
    }


    return render(request, 'webtoonitda/show_best_episodes_by_points.html', context)

    # 2. csv 저장된 csv 파일에서 가져와서 보여주기

    # 저장된 csv 파일에서 가져오기
    # df = pd.read_csv('C:\MyJupiter\삼성멀티캠\_Django\workspace\webtoonsite\webtoon1\전독시_인기_에피소드.csv', index_col = 0)

    # DB 에 data를 생성하기
    # for i in range(10):
    #     BestEpisodes.objects.create(title=df['Title'][i], point=df['Point'][i], participant=df['Participant'][i])
    #     print(df['Point'][i])
    #
    # # DB 에서 데이터 가져오기
    # all_episode = BestEpisodes.objects.all().order_by('-id')

    context = {'df': df[:10].to_html(justify='center')}
    return render(request, 'webtoonitda/show_best_episodes_by_points.html', context)


#윤지
def ep_review(request):
  return render(request, 'webtoonitda/ep_review.html')


import pandas as pd
def ep_search(request):
    if request.method == 'POST':
          keyword = request.POST.get('keyword')
          print("ep_review POST" + keyword)
          DATA_DIR = os.getcwd() + "/media/kr/"

          print("Read csv file.")
          filepath = DATA_DIR + "omniscient-reader_Episode_kr_21.csv"
          df = pd.read_csv(filepath)

          test = df[df['Review'].str.contains(keyword)]  # df에 keyword파라미터 받음
          df = test.sample(20)  # 원하는 개수만큼 추출
          print(type(df))



          context = {
              'df': df[:20].to_html(justify='center')


          } # 템플릿에 전달할 데이터를 세팅할 수 있는 오브젝트

          # return HttpResponse("ep_search keyword:" + title)
    return render(request, 'webtoonitda/show_21_episodes.html', context)
# )

웹서비스/webtoonitda/webtoonitda/views/review_webtoon.py
# ---
# jupyter:
#   jupytext:
#     formats: ipynb,py:light
#     text_representation:
#       extension: .py
#       format_name: light
#       format_version: '1.5'
#       jupytext_version: 1.14.0
#   kernelspec:
#     display_name: nlp
#     language: python
#     name: nlp
# ---

# +
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.keys import Keys
from webdriver_manager.chrome import ChromeDriverManager
from bs4 import BeautifulSoup as bs
import requests
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
plt.rc('font', family='NanumGothic')
import os
import time
from glob import glob

pd.set_option("display.max_rows", 1000)
pd.set_option("display.max_columns", 1000)
pd.options.display.float_format = '{:.2f}'.format
# -

# +
def get_reviews(title, USE_CSV_FILE):
    """
    워드 클라우드 키워드 반환하는 함수
    """
    DATA_DIR = os.getcwd() + "/media/"

    if USE_CSV_FILE:
        print("Read csv file.")
        filepath = DATA_DIR + "omniscient-reader_Episode_kr_21.csv"
        df = pd.read_csv(filepath)

    test = df[df['Review'].str.contains(title)] #df에 title파라미터 받음
    a=test.sample(5) #원하는 개수만큼 추출
    print(a)

    return a


# def get_top10_num_reviews(chromedriver_path, platform, lang, titleId, num_episodes, USE_CSV_FILE):
#     """
#     댓글 개수가 높은 에피소드 top10을 반환하는 함수
#     """
#     DATA_DIR = os.getcwd() + "/media/"
#
#     if USE_CSV_FILE:
#         print("Read csv file.")
#         filepath = DATA_DIR + "kr_전지적 독자 시점_num_reviews.csv"
#         df = pd.read_csv(filepath)
#     else:
#         df = get_num_reviews(chromedriver_path, lang, titleId, num_episodes, DATA_DIR)
#
#     df_top10 = df.sort_values(by=['Num_reviews', 'Episode'], ascending=False)
#     df_top10 = df_top10.drop(['Num_pages'], axis=1)
#     df_top10 = df_top10.set_index(keys='Episode', drop=True)
#     print(df_top10[:10])
#
#     return df_top10[:10]

웹서비스/webtoonitda/templates/webtoonitda/service_summary.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}
<div class="container my-3">
    <h1> webtoon service summary</h1>

    <!--    {% if platform != 'naver' and webtoon != '전지적 독자 시점' %}-->
    <!--         <h4> 앗앗앗! {{webtoon}}에 대해 아직 준비된 서비스가 없습니다.</h4>-->
    <!--    {% else %}-->
    {% if lang == 'kr' %}
    <p class="mb-0"> 한글 , {{platform}} , {{webtoon}} 분석을 시작합니다.</p>
    {% elif lang == 'en' %}
    <p class="mb-0"> 영어 , {{platform}} , {{webtoon}} 분석을 시작합니다.</p>
    {% endif %}
    <!--    {% endif %}-->


</div>

<!-- Categories widget-->
<div class="card mb-4">
    <div class="card-header">Analysis Service Categories</div>
    <div class="card-body">
        <div class="row">
            <div class="col-6">
                <div class="alert alert-info">
                    <button type="button"></button>
                    <h4><strong>전체 댓글수 추이</strong></h4> <a
                        href="{% url 'webtoonitda:show_num_reviews' lang platform webtoon %}"
                        class="alert-link">전체 에피소드의 댓글수를 분석합니다(한글,영어)</a>
                </div>
            </div>
            <div class="col-6">
                <div class="alert alert-info">
                    <button type="button"></button>
                    <h4><strong>댓글수 에피소드 Top10</strong></h4> <a
                        href="{% url 'webtoonitda:show_best_episodes_by_reviews' lang platform webtoon %}"
                        class="alert-link">댓글수가 가장 많은 에피소드 Top10을 보여줍니다(한글)</a>
                </div>
            </div>
        </div>


        <div class="row">
            <div class="col-6">
                <div class="alert alert-info">
                    <button type="button"></button>
                    <h4><strong>전체 평점수/참여도 추이</strong></h4> <a
                        href="{% url 'webtoonitda:show_participants' lang platform webtoon %}" class="alert-link">
                    전체 에피소드의 평점수/참여도를 분석합니다</a>
                </div>
            </div>
            <div class="col-6">
                <div class="alert alert-info">
                    <button type="button"></button>
                    <h4><strong>평점수/참여도 에피소드 Top10</strong></h4> <a
                        href="{% url 'webtoonitda:show_best_episodes_by_points' lang platform webtoon %}"
                        class="alert-link">평점수/참여도 상위 에피소드 Top10을 보여줍니다(데이터 수집에 시간이 다소 소요됩니다)</a>
                </div>
            </div>
        </div>

         <div class="row">
            <div class="col-6">
                <div class="alert alert-info">
                    <button type="button"></button>
                    <h4><strong>댓글 원본 추출</strong></h4> <a
                        href="{% url 'webtoonitda:ep_review'%}" class="alert-link">
                    검색어를 입력하면 댓글 원본을 추출합니다</a>
                </div>
            </div>
            <div class="col-6">
                <div class="alert alert-info">
                    <button type="button"></button>
                    <h4><strong>전체 중요 키워드 Top10</strong></h4> <a
                        href="{% url 'webtoonitda:show_keywords' lang platform webtoon %}"
                        class="alert-link">전체 댓글에서 가장 많이 등장한 중요한 단어 Top10을 보여줍니다</a>
                </div>
            </div>
        </div>


        <div class="row">
            <div class="col-6">
                <div class="alert alert-info">
                    <button type="button"></button>
                    <h4><strong>단어간 유사도 측정</strong></h4> <a
                        href="{% url 'webtoonitda:show_similarity' %}" class="alert-link">
                    두 개의 단어간의 유사도를 측정합니다</a>
                </div>
            </div>
            <div class="col-6">
                <div class="alert alert-info">
                    <button type="button"></button>
                    <h4><strong>Topic별 유사 단어 추출</strong></h4> <a
                        href="{% url 'webtoonitda:show_topic_keywords' lang platform webtoon %}"
                        class="alert-link">Topic별로 문맥에 관련된 단어들을 추출합니다</a>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container my-3">

    <div class="d-grid gap-2">
        <button onclick="javascript:history.back();" class="btn btn-lg btn-danger" type="button">뒤로가기</button>
    </div>
</div>


{% endblock %}
{% block script %}
<script type='text/javascript'>

</script>
{% endblock %}

웹서비스/webtoonitda/templates/webtoonitda/show_21_episodes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>test</title>
</head>
<body>
{{df|safe}}

</body>
</html>

웹서비스/webtoonitda/templates/webtoonitda/show_best_episodes_by_reviews.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}
<!--<style>-->
<!--    h2 { text-align: center; }-->
<!--    h3 { text-align: right; }-->
<!--    h4 { text-align: left; }-->
<!--</style>-->

<div class="container my-3">
    <div class="row">
        <div class="col-6">
            {% if platform != 'naver' and webtoon != '전지적 독자 시점' %}
            <h2> 앗앗앗! {{webtoon}} 플랫폼 {{webtoon}}에 대해 아직 준비된 서비스가 없습니다.</h2>
            {% else %}
            <h2> 댓글수 에피소드 Top10</h2>
            {% if lang == 'kr' %}
            <h5> 한글 , {{platform}} , {{webtoon}} 분석 결과입니다.</h5><br>

            <h5><li> 프롤로그와 첫 화 에피소드에서 특별히 많은 댓글이 작성되었습니다.</li></h5>
            <h5><li> 40화에서 특별히 높은 댓글 수가 발견됩니다. </li></h5>
            <h5><li> 더 자세한 분석이 필요하시면 에피소드를 선택하세요.</li></h5>

            {% elif lang == 'en' %}

            <h5> 영어 , {{platform}} , {{webtoon}} 분석 결과입니다.</h5><br>
            {% endif %}
            {% endif %}

        </div>

    </div>


</div>
<form id="searchForm" method="get" action="{% url 'webtoonitda:index' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>

<!--{{ df|safe}}-->

<div class="row">
    <div class="col-9">

        {% if lang == 'kr' %}
        <!--    <h2> 한글</h2>-->
        <img src="/media/kr/kr_top10_num_reviews.png" style="max-width: 100%; height: auto;"/>
        {% elif lang == 'en' %}
        <!--    <h2> 영어</h2>-->
        <img src="/media/en/en_top10_num_reviews.png"/>
        {% else %}
        <!--    <h2> 다른 언어</h2>-->
        <h2> 앗! {{lang}}에 대해 아직 준비된 서비스가 없습니다.</h2>
        {% endif %}

    </div>

    <div class="col-3">
        <!-- Episode selection section-->
        <form action="{% url 'webtoonitda:episode_page'%}" method="POST">
            {% csrf_token %}
            <div class="card mb-4">
                <div class="card-header">Search</div>
                <div class="card-body">

                    <h5> 에피소드</h5>
                    <div class="input-group">
                        {% block script %}
                        <script type='text/javascript'>
                        function dropDown(){
                        var start = 1;
                        var end = 125;
                        document.write('<select class="form-select" id="selectbox_webtoon" name="episode" onchange="changeWebtoonSelect()">');
                        document.write('<option value="" selected disabled>에피소드를 선택하세요</option>');
                        for (var i = start ; i <= end; i++)
                            document.write('<option value="' + i + '">' + i + '</option>');
                            document.write("</select>");
                        }
                        dropDown();

                        </script>

                        {% endblock %}

                        <button type="submit" class="btn btn-primary" onclick="clickStartEpisodeAnalysis()">Go!
                        </button>
                    </div>


                </div>
            </div>
        </form>
    </div>

</div>


<div class="container my-3">
<div class="d-grid gap-2">
  <button onclick="javascript:history.back();" class="btn btn-lg btn-danger" type="button">뒤로가기</button>
</div>
</div>

</form>

{% endblock %}

웹서비스/webtoonitda/templates/webtoonitda/show_num_reviews.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}

<div class="container my-3">
    <div class="row my-3">
        <div class="col-6">
            {% if platform != 'naver' and webtoon != '전지적 독자 시점' %}
            <h2> 앗앗앗! {{webtoon}} 플랫폼 {{webtoon}}에 대해 아직 준비된 서비스가 없습니다.</h2>
            {% else %}
            <h2> 전체 에피소드 댓글 추이</h2>
            {% if lang == 'kr' %}
            <h5> 한글 , {{platform}} , {{webtoon}} 분석 결과입니다. </h5>
            <li> 한글 웹툰과 영어 웹툰 사이의 댓글 추이가 대체로 유사합니다.</li>
            <li> 한글 독자들이 더 많은 댓글을 작성하고 있습니다.</li>
            <li> 한글 영어 모두 시간이 지나면서 에피소드에 대한 댓글수가 감소합니다.</li>
            <li> 특정 에피소드(40화)의 경우 댓글수가 갑자기 증가하였습니다.</li>

            {% elif lang == 'en' %}
            <h5> 영어 , {{platform}} , {{webtoon}} 분석 결과입니다.</h5>
            {% endif %}
            {% endif %}

        </div>
    </div>


</div>
<form id="searchForm" method="get" action="{% url 'webtoonitda:index' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>

{{ df|safe}}

<div class="row">
    <div class="col-9">


        {% if lang == 'kr' %}
        <!--    <h2> 한글</h2>-->
        <!--    <img src="/media/kr_iplot_num_reviews.png"/>-->
        <img src="/media/kr/kr_en_num_reviews.png"/>

        {% elif lang == 'en' %}
        <!--    <h2> 영어</h2>-->
        <img src="/media/en/en_num_reviews.png"/>
        {% else %}
        <!--    <h2> 다른 언어</h2>-->
        <h2> 앗! {{lang}}에 대해 아직 준비된 서비스가 없습니다.</h2>
        {% endif %}

    </div>
    <div class="col-3">
        <!-- Episode selection section-->
        <form action="{% url 'webtoonitda:episode_page'%}" method="POST">
            {% csrf_token %}
            <div class="card mb-4">
                <div class="card-header">Search</div>
                <div class="card-body">

                    <h5> 에피소드</h5>
                    <div class="input-group">
                        {% block script %}
                        <script type='text/javascript'>
                        function dropDown(){
                        var start = 1;
                        var end = 125;
                        document.write('<select class="form-select" id="selectbox_webtoon" name="episode" onchange="changeWebtoonSelect()">');
                        document.write('<option value="" selected disabled>에피소드를 선택하세요</option>');
                        for (var i = start ; i <= end; i++)
                            document.write('<option value="' + i + '">' + i + '</option>');
                            document.write("</select>");
                        }
                        dropDown();



                        </script>

                        {% endblock %}

                        <button type="submit" class="btn btn-primary" onclick="clickStartEpisodeAnalysis()">Go!
                        </button>
                    </div>


                </div>
            </div>
        </form>
    </div>
</div>

<div class="container my-3">
    <div class="d-grid gap-2">
        <button onclick="javascript:history.back();" class="btn btn-lg btn-danger" type="button">뒤로가기</button>
    </div>
</div>

</form>

{% endblock %}

웹서비스/webtoonitda/templates/webtoonitda/show_participants.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}

<style>
    div.background{
    font-size: 20px;
}

</style>


<div class="container my-3">
    <div class="row my-3">
        <div class="col-6">
            <h3> 전체 평점 참여도 추이</h3>
            {% if lang == 'kr' %}
            <h5> 한글 , {{platform}} , {{webtoon}} 분석을 시작합니다.</h5>
            {% elif lang == 'en' %}
            <h5> 영어 , {{platform}} , {{webtoon}} 분석을 시작합니다.</h5>
            {% endif %}

            <h5> 한글 , {{platform}} , {{webtoon}} 분석 결과입니다.  </h5>
            <li> 첫 프롤로그와 1화를 제외하고 105화에서 참여도가 급격히 높아졌습니다.  </li>
            <li> 105화를 더 자세히 분석해보세요.</li>

        </div>
    </div>


</div>
<form id="searchForm" method="get" action="{% url 'webtoonitda:index' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>


<div class="row">
    <div class="col-9">
<div>
    <img src="/media/kr/kr_전지적 독자 시점_participant.png"/>
</div>
    </div>
    <div class="col-3">
        <!-- Episode selection section-->
        <form action="{% url 'webtoonitda:episode_page'%}" method="POST">
            {% csrf_token %}
            <div class="card mb-4">
                <div class="card-header">Search</div>
                <div class="card-body">

                    <h5> 에피소드</h5>
                    <div class="input-group">
                        {% block script %}
                        <script type='text/javascript'>
                        function dropDown(){
                        var start = 1;
                        var end = 125;
                        document.write('<select class="form-select" id="selectbox_webtoon" name="episode" onchange="changeWebtoonSelect()">');
                        document.write('<option value="" selected disabled>에피소드를 선택하세요</option>');
                        for (var i = start ; i <= end; i++)
                            document.write('<option value="' + i + '">' + i + '</option>');
                            document.write("</select>");
                        }
                        dropDown();

                        </script>

                        {% endblock %}

                        <button type="submit" class="btn btn-primary" onclick="clickStartEpisodeAnalysis()">Go!
                        </button>
                    </div>


                </div>
            </div>
        </form>
    </div>
</div>





<div class="container my-3">
    <div class="d-grid gap-2">
        <button onclick="javascript:history.back();" class="btn btn-lg btn-danger" type="button">뒤로가기</button>
    </div>
</div>

</form>

{% endblock %}